2022-12-20 21:39:58,012 INFO: Blog startup [in D:\Coding\CS50x_Harvard\Final_Project\Blog\app\__init__.py:54]
2022-12-20 21:46:31,016 INFO: Blog startup [in D:\Coding\CS50x_Harvard\Final_Project\Blog\app\__init__.py:54]
2022-12-20 21:48:37,649 INFO: Blog startup [in D:\Coding\CS50x_Harvard\Final_Project\Blog\app\__init__.py:54]
2022-12-20 21:50:49,252 INFO: Blog startup [in D:\Coding\CS50x_Harvard\Final_Project\Blog\app\__init__.py:54]
2022-12-20 22:18:16,951 INFO: Blog startup [in D:\Coding\CS50x_Harvard\Final_Project\Blog\app\__init__.py:54]
2022-12-20 22:50:53,299 ERROR: Exception on /index [POST] [in C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\app\routes.py", line 34, in index
    db.session.commit()
  File "<string>", line 2, in commit
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\sqlalchemy\orm\session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\sqlalchemy\orm\session.py", line 839, in commit
    self.session.dispatch.after_commit(self.session)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\sqlalchemy\event\attr.py", line 247, in __call__
    fn(*args, **kw)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\app\models.py", line 35, in after_commit
    add_to_index(obj.__tablename__, obj)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\app\search.py", line 9, in add_to_index
    current_app.elasticsearch.index(index = index,
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\elasticsearch\_sync\client\utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\elasticsearch\_sync\client\__init__.py", line 2265, in index
    return self.perform_request(  # type: ignore[return-value]
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\elasticsearch\_sync\client\_base.py", line 286, in perform_request
    meta, resp_body = self.transport.perform_request(
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\elastic_transport\_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\elastic_transport\_node\_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x0000014AB5F1C250>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение))
2022-12-22 00:13:32,390 INFO: Blog startup [in D:\Coding\CS50x_Harvard\Final_Project\Blog\app\__init__.py:54]
2022-12-22 00:14:16,181 INFO: Blog startup [in D:\Coding\CS50x_Harvard\Final_Project\Blog\app\__init__.py:54]
2022-12-22 00:15:54,661 INFO: Blog startup [in D:\Coding\CS50x_Harvard\Final_Project\Blog\app\__init__.py:54]
2022-12-22 00:28:04,941 INFO: Blog startup [in D:\Coding\CS50x_Harvard\Final_Project\Blog\app\__init__.py:54]
